title: Tarun Komirishetty
theme: jekyll-theme-minimal

plugins:
  - jekyll-feed

exclude:
  - README.md

sass:
  style: compressed

include:
  - assets/css

defaults:
  - scope:
      path: ""
    values:
      favicon: "/assets/img/favicon.ico"



